import assert from "node:assert/strict";
import { createLaunchRuntime } from "../src/runtime/index.js";
import { createHomePage, createJoinPage, createDashboardPage, createSparkPage, createCouncilPage, createFamousReadyExport } from "../src/application/index.js";
const runtime = createLaunchRuntime({ ...process.env, STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? "demo", STRIPE_MONTHLY_7_PRICE_ID: process.env.STRIPE_MONTHLY_7_PRICE_ID ?? "price_monthly", STRIPE_YEARLY_70_PRICE_ID: process.env.STRIPE_YEARLY_70_PRICE_ID ?? "price_yearly" });
const { member, session } = await runtime.auth.signUp("demo@humanitylaws.com", "Demo Member");
assert.equal(session.authenticated, true);
const checkout = await runtime.checkout.createCheckout({ memberId: member.memberId, planId: "MONTHLY_7", successUrl: "/success", cancelUrl: "/cancel" });
assert.equal(checkout.success, true);
const active = await runtime.subscriptionStatus.markActiveFromPayment(member.memberId);
assert.equal(active.membershipStatus, "ACTIVE");
const spark = await runtime.spark.nextSpark(active.memberId);
assert.equal(createSparkPage(spark).pageId, "spark");
const council = await runtime.council.respond(active.memberId, "Help me begin well.");
assert.ok(council.synthesis.length > 0);
assert.equal(createHomePage().title, "A calm home for daily human growth.");
assert.equal(createJoinPage().pageId, "join");
assert.equal(createDashboardPage(active).pageId, "dashboard");
assert.equal(createCouncilPage(council.synthesis).pageId, "council");
assert.ok(createFamousReadyExport().length >= 14);
console.log(JSON.stringify({ smokeTestPassed: true, activeMember: active.memberId, launchReady: false, lifecycleAdvanced: false }, null, 2));
